CREATE TABLE IF NOT EXISTS `field_access_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_type` VARCHAR(32) NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  `fields_json` JSON NOT NULL,
  `reason` TEXT NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'pending',
  `requested_by_user_id` INT UNSIGNED NOT NULL,
  `requested_by_name` VARCHAR(191) NULL,
  `requested_by_email` VARCHAR(191) NULL,
  `l1_user_id` INT UNSIGNED NULL,
  `l1_email` VARCHAR(191) NULL,
  `l1_name` VARCHAR(191) NULL,
  `decided_by_user_id` INT UNSIGNED NULL,
  `decided_by_name` VARCHAR(191) NULL,
  `decision_note` TEXT NULL,
  `granted_fields_json` JSON NULL,
  `expires_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_far_item` (`item_type`, `item_id`),
  KEY `idx_far_status` (`status`),
  KEY `idx_far_l1_email` (`l1_email`),
  KEY `idx_far_l1_user` (`l1_user_id`),
  KEY `idx_far_requester` (`requested_by_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
